### PR TITLE
allow Laravel 6

### PR DESCRIPTION
**Pull request by browner12**
looking through the Laravel 6 upgrade guide, it doesn't seem like anything in this package should be affected.

### CODE REVIEW

**Comment by MoeCasts** [comment]
@browner12 can you fork the package and publish like a new package? 
The author seems to be inactive

**Comment by webwizo** [comment]
Thank you guys for you effort. 👍

**Comment by MoeCasts** [comment]
@webwizo the package haven't been updated at packagist. Can you update it?

**Comment by webwizo** [comment]
@MoeCasts Are you sure?
It's been updated. I can see it there.

**Comment by MoeCasts** [comment]
@webwizo i can see it now.

**Pull request merged**
