### PR TITLE
Multiple laravel versions

### PR DESCRIPTION
**Pull request by abr4xas**

### CODE REVIEW

**Comment by abr4xas** [comment]
@webwizo ping

**Comment by Nuranto** [comment]
@abr4xas Suggestion to add to the PR, while waiting for @webwizo : 
https://github.com/webwizo/laravel-shortcodes/issues/43

**Comment by webwizo** [comment]
I'm sorry @abr4xas for delay.
My priorities have been changed, it's been almost a year I didn't work on any Laravel Project.

My apologies.

**Comment by abr4xas** [comment]
@webwizo no problem!! :smiley:

**Pull request merged**
